#### Exclude
exclude: [".rvmrc", ".rbenv-version", "README.md", "README_en.md", "Rakefile", "changelog.md"]

#### Code Highlighter
# 'pygments' is unsupported on GitHub Pages now.
highlighter: rouge

#### Permalink
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: pretty

#### Markdown Processors
# 'redcarpet' is unsupported on GitHub Pages now.
markdown: kramdown
kramdown:
    input: GFM

#### Default Attributes
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

#### Pagination
paginate: 20

#### Site
title : kwang's blog
tagline: 个人技术总结
assets: /assets
url:
baseurl:

#### Language
language: zh-CN    ## blog site languages: en, zh-CN, zh-TW, de

#### Menu
menu:
  Home: /
  Archives: /archives
  About: /about
## you can create `tags` and `categories` folders (I had created them already).
## And create a `index.md` file in each of them.
## set `front-matter`as
## layout: tags (or categories)
## title: tags (or categories)
## ---

#### Widgets
widgets:
- category
- tag
- tagcloud
- links
- douban
- github-card
- rss
## provide seven widgets:github-card,category,tag,rss,archive,tagcloud,links,weibo,douban


#### RSS
    #rss: /atom.xml ## RSS address.

#### Image
imglogo:
  enable: true             ## display image logo true/false.
  src: img/logo.png        ## `.svg` and `.png` are recommended,please put image into the theme folder `/jacman/source/img`.
#favicon: img/favicon.ico   ## size:32px*32px,`.ico` is recommended,please put image into the theme folder `/jacman/source/img`.
#apple_icon: img/jacman.jpg ## size:114px*114px,please put image into the theme folder `/jacman/source/img`.
#author_img: img/author.jpg ## size:220px*220px.display author avatar picture.if don't want to display,please don't set this.
#banner_img: #img/banner.jpg ## size:1920px*200px+. Banner Picture

#### index post is expanding or not
index:
  expand: true           ## default is unexpanding,so you can only see the short description of each post.
  excerpt_link: Read More

close_aside: false  #close sidebar in post page if true
mathjax: true      #enable mathjax if true
share_to: true #enable share-to buttons if true

#### Author information
author:
  name: kwang      ## e.g. wuchong Author name
  intro_line1:  "个人介绍"    ## your introduction on the bottom of the page
  intro_line2:  "个人介绍二"  ## the 2nd line
  weibo:      ## e.g. wuchong1014 or 2176287895 for http://weibo.com/2176287895
  weibo_verifier:  ## e.g. b3593ceb Your weibo-show widget verifier ,if you use weibo-show it is needed.
  tsina:      ## e.g. 2176287895  Your weibo ID,It will be used in share button.
  douban:     ## e.g. wuchong1014 or your id for https://www.douban.com/people/wuchong1014
  zhihu:      ## e.g. jark  for http://www.zhihu.com/people/jark
  email:      ## e.g. imjark@gmail.com
  twitter:    ## e.g. jarkwu for https://twitter.com/jarkwu
  github:     ## e.g. wuchong for https://github.com/wuchong
  facebook:   ## e.g. imjark for https://facebook.com/imjark
  linkedin:   ## e.g. wuchong1014 for https://www.linkedin.com/in/wuchong1014
  google_plus:    ## e.g. "111190881341800841449" for https://plus.google.com/u/0/111190881341800841449, the "" is needed!
  stackoverflow:  ## e.g. 3222790 for http://stackoverflow.com/users/3222790/jark
## if you set them, the corresponding  share button will show on the footer

#### Toc
toc:
  article: true   ## show contents in article.
  aside: true     ## show contents in aside.
## you can set both of the value to true of neither of them.
## if you don't want display contents in a specified post,you can modify `front-matter` and add `toc: false`.

#### Links
links:
  #码农圈: https://coderq.com
  #Jark's Blog: http://wuchong.me


#simple_jekyll_search:
#  enable: true
#  fulltext: false

gems:
 - jemoji

